// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package jobs

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID        int32
	JobHash   []byte
	Page      string
	Title     string
	CreatedAt pgtype.Timestamp
}
