// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package jobs

import (
	"context"
)

const listAllJobs = `-- name: ListAllJobs :many
SELECT id, job_hash, page, title, created_at FROM jobs
`

func (q *Queries) ListAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobHash,
			&i.Page,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
