// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package jobs

import (
	"context"
)

const deleteJob = `-- name: DeleteJob :exec
UPDATE jobs
SET deleted = TRUE,
    deleted_at = NOW()
WHERE
    job_hash = $1 AND
    deleted = FALSE
`

func (q *Queries) DeleteJob(ctx context.Context, jobHash []byte) error {
	_, err := q.db.Exec(ctx, deleteJob, jobHash)
	return err
}

const getAllJobs = `-- name: GetAllJobs :many
SELECT id, job_hash, page, title, created_at, deleted, deleted_at
FROM
    jobs
WHERE
    deleted <> FALSE
`

func (q *Queries) GetAllJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getAllJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobHash,
			&i.Page,
			&i.Title,
			&i.CreatedAt,
			&i.Deleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO jobs (job_hash, page, title)
VALUES($1, $2, $3)
`

type InsertJobParams struct {
	JobHash []byte
	Page    string
	Title   string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.Exec(ctx, insertJob, arg.JobHash, arg.Page, arg.Title)
	return err
}
